# Rename this file to config.yml and fill the fields with your information

# The GitHub token for your account
github_token:

# The port where the server will be running
port: 3000

# The WakaTime API Key for your account
wakatime_api_key:

# For the /spotify route
spotify_username:
